image: openjdk:11  # Use OpenJDK 11 Docker image for the build environment

before_script:
  - apt-get update -y  # Update package list
  - apt-get install -y curl gnupg  # Install necessary packages
  - curl -sL https://dl.bintray.com/sbt/debian/sbt-1.5.5.deb -o sbt.deb  # Download sbt
  - dpkg -i sbt.deb  # Install sbt
  - sbt sbtVersion  # Check that sbt is installed and its version
  - java -version  # Check Java version

build:
  script:
    - sbt compile  # Compile the project with SBT
